openinghours/urls.py
from django.urls import path
from openinghours.views import CurrentlyOpenView
from openinghours.views_edit import OpeningHoursEditView

urlpatterns = [
     path('', CurrentlyOpenView.as_view(),
          name='openinghours_currently_open'),
     path('edit/<int:pk>', OpeningHoursEditView.as_view(),
          name='openinghours_edit'),
]

openinghours/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from openinghours.app_settings import PREMISES_MODEL

# isoweekday
WEEKDAYS = [
    (1, _("Monday")),
    (2, _("Tuesday")),
    (3, _("Wednesday")),
    (4, _("Thursday")),
    (5, _("Friday")),
    (6, _("Saturday")),
    (7, _("Sunday")),
]


class Company(models.Model):
    """
    Default model for company premises, which can be
    replaced using OPENINGHOURS_PREMISES_MODEL.
    """
    class Meta:
        verbose_name = _('Company')
        verbose_name_plural = _('Companies')
        swappable = 'OPENINGHOURS_PREMISES_MODEL'

    name = models.CharField(_('Name'), max_length=100)
    slug = models.SlugField(_('Slug'), unique=True)
    logo = models.FileField(_('Logo'), upload_to='logo', null=True, blank=True)

    def __str__(self):
        return self.name


class OpeningHours(models.Model):
    """
    Store opening times of company premises,
    defined on a daily basis (per day) using one or more
    start and end times of opening slots.
    """
    class Meta:
        verbose_name = _('Opening Hours')  # plurale tantum
        verbose_name_plural = _('Opening Hours')
        ordering = ['company', 'weekday', 'from_hour']

    company = models.ForeignKey(PREMISES_MODEL, verbose_name=_('Company'),
                                on_delete=models.CASCADE)
    weekday = models.IntegerField(_('Weekday'), choices=WEEKDAYS)
    from_hour = models.TimeField(_('Opening'))
    to_hour = models.TimeField(_('Closing'))

    def __str__(self):
        return _("%(premises)s %(weekday)s (%(from_hour)s - %(to_hour)s)") % {
            'premises': self.company,
            'weekday': self.weekday,
            'from_hour': self.from_hour,
            'to_hour': self.to_hour
        }


class ClosingRules(models.Model):
    """
    Used to overrule the OpeningHours. This will "close" the store due to
    public holiday, annual closing or private party, etc.
    """
    class Meta:
        verbose_name = _('Closing Rule')
        verbose_name_plural = _('Closing Rules')
        ordering = ['start']

    company = models.ForeignKey(PREMISES_MODEL, verbose_name=_('Company'),
                                on_delete=models.CASCADE)
    start = models.DateTimeField(_('Start'))
    end = models.DateTimeField(_('End'))
    reason = models.TextField(_('Reason'), null=True, blank=True)

    def __str__(self):
        return _("%(premises)s is closed from %(start)s to %(end)s\
        due to %(reason)s") % {
            'premises': self.company.name,
            'start': str(self.start),
            'end': str(self.end),
            'reason': self.reason
        }

openinghours/forms.py
"""Editing form for opening hours

Front-end untrusted end user grade UX aimed at business directory sites.

UX supports up to 2 sets of opening hours per day optimised for common stories:
9 till 5, closed for lunch, open till late, Saturday morning-closed on Sunday
"""

from django import forms
from datetime import time


def str_to_time(s):
    """ Turns strings like '08:30' to time objects """
    return time(*[int(x) for x in s.split(':')])


def time_to_str(t):
    """ Turns time objects to strings like '08:30' """
    return t.strftime('%H:%M')


def time_choices():
    """Return digital time choices every half hour from 00:00 to 23:30."""
    hours = list(range(0, 24))
    times = []
    for h in hours:
        hour = str(h).zfill(2)
        times.append(hour+':00')
        times.append(hour+':30')
    return list(zip(times, times))


TIME_CHOICES = time_choices()


class Slot(forms.Form):
    opens = forms.ChoiceField(choices=TIME_CHOICES)
    shuts = forms.ChoiceField(choices=TIME_CHOICES)

openinghours/views.py
from django.conf import settings
from django.views.generic import TemplateView
from openinghours.utils import get_premises_model


class CurrentlyOpenView(TemplateView):
    model = get_premises_model()
    template_name = "openinghours/index.html"

    def get_context_data(self, **kwargs):
        context = super(CurrentlyOpenView, self).get_context_data(**kwargs)
        context['location'] = self.model.objects.first()
        context['timezone'] = settings.TIME_ZONE
        return context

openinghours/templates/openinghours/base.html
<!DOCTYPE HTML>
<html>
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
{% block js %}
{% endblock %}
</head>
<body>
<div class="container">
<h1><i class="glyphicon glyphicon-time"></i> Opening hours</h1>
<p>Use cases and examples for django-openinghours.
<ul class="nav nav-tabs">
<li{% if not days %} class="active"{% endif %}>
    <a href="/openinghours/">template tags</a></li>
<li{% if days %} class="active"{% endif %}>
    <a href="/openinghours/edit/1">editing form</a></li>
</ul>
{% block content %}
{% endblock %}
</div>
</body>
</html>

openinghours/templates/openinghours/companyOpeningHoursListConcise.html
<dl>
{% for set in days %}
	<dt>{{ set.day_names }}:</dt>
		<dd>{{ set.hours }}</dd>
{% endfor %}
</dl>

openinghours/templates/openinghours/edit_base.html
{% extends "openinghours/base.html" %}
{% block title %}Opening hours{% endblock %}
{% block js %}
<script src="//code.jquery.com/jquery.min.js"></script>
{% endblock %}
{% block content %}
{% include 'openinghours/edit_form.html' %}
{% endblock %}

openinghours/templates/openinghours/edit_form.html
{% load i18n %}

<script>
$(function(){
    // Toggle display for 2nd set of hours
    $('.set2').toggle($('#two_sets').is(':checked'));
    $('#two_sets').on('click', function(){
        $('.set2').toggle();
    });


    // Shortcut to repeat Monday's hours for rest of the week
    $('#repeat').on('click', function(e){
        e.preventDefault();
        // Disable until needed
        $(this).addClass('disabled');
        // Get Monday values
        var opens  = $('#id_day1_1-opens option:selected').val();
        var shuts  = $('#id_day1_1-shuts option:selected').val();
        var opens2 = $('#id_day1_2-opens option:selected').val();
        var shuts2 = $('#id_day1_2-shuts option:selected').val();
        // Apply to rest of week
        $('.day').each(function(index, element){
            var i = index + 1;
            $('#id_day'+i+'_1-opens').val(opens);
            $('#id_day'+i+'_1-shuts').val(shuts);
            $('#id_day'+i+'_2-opens').val(opens2);
            $('#id_day'+i+'_2-shuts').val(shuts2);
        });
    });
    // Enable repeat shortcut now a time is selected
    $('select').on('click', function(){
        $('#repeat').removeClass('disabled');
    });


    // Disable time selection for a day if closed
    var closed = function(e){
        $(e).parents('.day').find('select').prop('disabled', e.checked);
    }
    $('.closed').each(function(){ closed(this); });
    $('.closed').on('click', function(){ closed(this); });
})
</script>

<style>
.weekday{display:inline-block;width:6em}
label{font-weight:normal}
form{padding-top:2em}
</style>

<form method="POST" action="#">
    {% for day in days %}
    <div class="day">
        <span class="set1">
            <span class="weekday text-muted text-right">
            {{ day.name }}</span>
            {{ day.slot1.opens }} - {{ day.slot1.shuts }}</span>
        <span class="set2"><span class="small text-muted">{% trans 'and' %}</span>
            {{ day.slot2.opens }} - {{ day.slot2.shuts }}</span>
        <label><input type="checkbox" class="closed"
            id="closed{{ day.number }}"
            {% if day.closed %}checked{% endif %}> {% trans 'Closed' %}</label>
        {% if forloop.first %}
            <button class="btn btn-default btn-xs" id="repeat">
                {% trans 'Apply to all days' %}</button>
        {% endif %}
    </div>
    {% endfor %}
    <p><label><input type="checkbox" id="two_sets"
        {% if two_sets %}checked{% endif %}>
        {% trans 'There are 2 sets of hours for 1 day.' %}</label>
    <p>
        <button class="btn btn-primary">{% trans 'Apply' %}</button>
        <a href="../" class="btn btn-default">{% trans 'Cancel' %}</a>
    {% csrf_token %}
</form>

openinghours/templates/openinghours/form.html
{% extends "openinghours/base.html" %}
{% block title %}Opening hours{% endblock %}
{% block js %}
<script src="//code.jquery.com/jquery.min.js"></script>
<script>
$(function(){
    // Toggle display for 2nd set of hours
    $('.set2').toggle($('#two_sets').is(':checked'));
    $('#two_sets').on('click', function(){
        $('.set2').toggle();
    });
    
    
    // Shortcut to repeat Monday's hours for rest of the week
    $('#repeat').on('click', function(e){
        e.preventDefault();
        // Disable until needed
        $(this).addClass('disabled');
        // Get Monday values
        var opens  = $('#id_day1_1-opens option:selected').val();
        var shuts  = $('#id_day1_1-shuts option:selected').val();
        var opens2 = $('#id_day1_2-opens option:selected').val();
        var shuts2 = $('#id_day1_2-shuts option:selected').val();
        // Apply to rest of week
        $('.day').each(function(index, element){
            var i = index + 1;
            $('#id_day'+i+'_1-opens').val(opens);
            $('#id_day'+i+'_1-shuts').val(shuts);
            $('#id_day'+i+'_2-opens').val(opens2);
            $('#id_day'+i+'_2-shuts').val(shuts2);
        });
    });
    // Enable repeat shortcut now a time is selected
    $('select').on('click', function(){
        $('#repeat').removeClass('disabled');
    });
    
    
    // Disable time selection for a day if closed
    var closed = function(e){
        $(e).parents('.day').find('select').prop('disabled', e.checked);
    }
    $('.closed').each(function(){ closed(this); });
    $('.closed').on('click', function(){ closed(this); });
})
</script>
<style>
.weekday{display:inline-block;width:6em}
label{font-weight:normal}
form{padding-top:2em}
</style>
{% endblock %}

{% block content %}
<form method="POST" action="#">
    {% for day in week %}
    <div class="day">
        <span class="set1">
            <span class="weekday text-muted text-right">
            {{ day.weekday.1 }}</span>
            {{ day.slot1.opens }} - {{ day.slot1.shuts }}</span>
        <span class="set2"><span class="small text-muted">and</span>  
            {{ day.slot2.opens }} - {{ day.slot2.shuts }}</span>
        <label><input type="checkbox" class="closed"
            id="closed{{ day.weekday.0 }}"
            {% if day.closed %}checked{% endif %}> Closed</label>
        {% if forloop.first %}
            <button class="btn btn-default btn-xs" id="repeat">Apply to all days</button>
        {% endif %}
    </div>
    {% endfor %}
    <p><label><input type="checkbox" id="two_sets"
        {% if two_sets %}checked{% endif %}>
        There are 2 sets of hours for 1 day.</label>
    <p>
        <button class="btn btn-primary">Apply</button>
        <a href="../" class="btn btn-default">Cancel</a>
    {% csrf_token %}
</form>
{% endblock %}

openinghours/templates/openinghours/index.html
{% extends "openinghours/base.html" %}
{% load i18n %}
{% load openinghours_tags %}

{% block content %}

<h2>Check current situation</h2>

{% verbatim %}
<pre>
{% is_open location as open %}
{% if open %}
    Come in, we're open!
{% else %}
    Sorry, we're closed.
    Reopening
    {% next_time_open location as next %}
    {{ next.get_weekday_display }} {{ next.from_hour }}
{% endif %}
</pre>
{% endverbatim %}

<p><b>{{ location.name }}</b><br>
    In {{ timezone }} it is now {% now "SHORT_DATETIME_FORMAT" %}
{% is_open location as open %}
{% if open %}
	<div class="alert alert-success">Come in, we're open!</div>
{% else %}
	<div class="alert alert-warning">Sorry, we're closed.
        Reopening
        {% next_time_open location as next %}
        {{ next.get_weekday_display }} {{ next.from_hour }}
    </div>
{% endif %}

<h2>Display opening hours</h2>

{% verbatim %}
<pre>{% opening_hours location %}</pre>
{% endverbatim %}

{% opening_hours location %}
<hr>
<p>Concise opening hours:</p>
{% verbatim %}
<pre>{% opening_hours location concise=1 %}</pre>
{% endverbatim %}

{% opening_hours location concise=1 %}

{% endblock %}

openinghours/templates/openinghours/opening_hours_list.html
<table class="table table-striped table-hover">
{% for day in days %}
	<tr>
        <th>{% ifchanged %}{{ day.name }}{% endifchanged %}</th>
        <td>{{ day.hours }}</td>
    </tr>
{% empty %}
	Sorry, we're closed.
{% endfor %}
</table>